export interface Project {
  title: string
  slug: string
  category: string
  description: string
  longDescription: string
  technologies: string[]
  features: string[]
  image: string
  github?: string
  liveUrl?: string
  featured?: boolean
}

export const projects: Project[] = [
  // ============ FEATURED PROJECTS ============
  {
    title: "SAVIOUR 2.0",
    slug: "saviour-2-0",
    category: "Disaster Management Platform",
    description:
      "A full-stack disaster management platform providing real-time emergency alerts, location-based shelter finding, resource tracking, and community coordination to improve disaster response and save lives.",
    longDescription:
      "SAVIOUR 2.0 is a comprehensive disaster management system that revolutionizes emergency response coordination through advanced technology integration. The platform serves as a critical infrastructure for disaster preparedness, response, and recovery operations. It features real-time communication systems, advanced resource tracking capabilities, and community engagement tools that work together to create a robust emergency response network. The system includes predictive analytics for disaster forecasting, automated alert systems, and integration with government emergency services. Built with scalability in mind, it can handle large-scale disasters while maintaining performance and reliability. The platform supports multiple user roles including citizens, volunteers, and administrators, each with tailored dashboards and functionalities.",
    technologies: [
      "React",
      "Node.js",
      "Firebase",
      "MongoDB",
      "Tailwind CSS",
      "Real-time APIs",
      "Push Notifications",
      "WebSocket",
      "PWA",
      "Google Maps API",
    ],
    features: [
      "Real-time emergency coordination and SOS alert systems",
      "Advanced user location tracking and mapping with GPS",
      "Intelligent nearby shelter and resource finder",
      "Comprehensive admin dashboard for command centers",
      "Community communication and safety check-in system",
      "Detailed safety instructions and preparedness guidelines",
      "Multi-device support (Web, iOS, Android) with PWA",
      "Secure contact and location data management",
      "Integration with government emergency services",
      "Predictive analytics for disaster forecasting",
      "Automated notification systems for timely alerts",
      "Resource allocation and inventory tracking tools",
      "Volunteer coordination and management system",
      "Post-disaster recovery planning and reporting tools",
    ],
    image: "/saviour.jpg",
    github: "https://github.com/Ravikumar-2016/Saviour-2.O",
    liveUrl: "https://saviour-ten.vercel.app/",
    featured: true,
  },
  {
    title: "FarmEase",
    slug: "farmease",
    category: "Agricultural Intelligence Platform",
    description:
      "A comprehensive AI-powered agriculture platform connecting farmers, laborers, and agricultural employees with intelligent crop recommendations, real-time market data, weather integration, and workforce management.",
    longDescription:
      "FarmEase is a revolutionary agricultural intelligence platform designed to transform modern farming through AI-powered insights, real-time data integration, and intelligent connectivity. Serving as a unified ecosystem for farmers, agricultural workers, support staff, and administrators, FarmEase streamlines operations, maximizes yields, and creates meaningful connections across the agricultural supply chain. The platform features 95%+ accurate crop and fertilizer recommendations based on soil, climate, and environmental data. With hyperlocal weather integration, live government-verified market prices, and the AgroBridge workforce matching system, FarmEase addresses critical challenges faced by modern farmers while providing growth opportunities for the entire agricultural community.",
    technologies: [
      "Next.js 15",
      "TypeScript",
      "Node.js",
      "MongoDB Atlas",
      "Tailwind CSS",
      "Framer Motion",
      "Weather API",
      "JWT Authentication",
      "Machine Learning",
      "Radix UI",
    ],
    features: [
      "Multi-role ecosystem for Farmers, Laborers, Employees, and Admins",
      "AI-powered crop and fertilizer recommendations (95%+ accuracy)",
      "Hyperlocal weather integration with 24-hour and 5-day forecasts",
      "Live government-verified market prices from agmarket.gov.in",
      "AgroBridge workforce hub for smart farmer-worker matching",
      "Advanced crop management and tracking with yield analytics",
      "Geo-based search for labor and agricultural services",
      "Real-time smart notifications for all stakeholders",
      "Comprehensive admin dashboard with analytics",
      "AI Disease Detection for crop health monitoring",
      "Query resolution and ticket support system",
      "Mobile-responsive design for field use",
    ],
    image: "/farmease.jpg",
    github: "https://github.com/Ravikumar-2016/FarmEase",
    liveUrl: "https://farm-ease-umber.vercel.app/",
    featured: true,
  },
  {
    title: "MeetTask AI",
    slug: "meettask-ai",
    category: "AI-Powered Productivity Tool",
    description:
      "An intelligent meeting transcription and task management system that converts meeting recordings to text with speaker diarization, enables task assignment, and streamlines team workflow management.",
    longDescription:
      "MeetTask AI is an innovative productivity platform that streamlines the meeting-to-task workflow for teams. The system allows managers to upload meeting recordings (audio or video), automatically transcribes them using AssemblyAI with speaker diarization, and facilitates task assignment to team members. Built with a modern tech stack including React 19, TypeScript, and serverless architecture, the platform features role-based access for managers and employees, real-time status updates via Firestore, and secure file submission through Google Drive integration. The application demonstrates expertise in full-stack development, third-party API integration, and modern cloud deployment practices.",
    technologies: [
      "React 19",
      "TypeScript",
      "Tailwind CSS 4",
      "Vite",
      "Firebase Auth",
      "Firebase Firestore",
      "AssemblyAI",
      "Cloudinary",
      "Vercel Serverless",
      "REST APIs",
    ],
    features: [
      "Audio/video meeting upload (MP3, WAV, M4A, MP4, MOV, WebM)",
      "AI-powered speech-to-text transcription with AssemblyAI",
      "Automatic speaker diarization and detection",
      "Manual speaker-to-employee mapping interface",
      "Role-based access control (Manager & Employee)",
      "Task creation with priority levels (Critical, High, Medium, Low)",
      "Real-time task status tracking (Pending → In Progress → Completed)",
      "Google Drive integration for file submissions",
      "Human-readable user IDs (e.g., MTAI001)",
      "Real-time updates via Firestore",
      "Secure JWT token verification",
      "Responsive design for desktop and mobile",
    ],
    image: "/MT-AI.jpg",
    github: "https://github.com/Ravikumar-2016/MeetTask-AI",
    liveUrl: "https://meet-task-ai.vercel.app/",
    featured: true,
  },
  // ============ OTHER PROJECTS ============
  {
    title: "SAVIOUR Mobile",
    slug: "saviour-mobile",
    category: "Mobile Application",
    description:
      "Cross-platform mobile companion for the SAVIOUR disaster management system, providing on-the-go emergency response capabilities with offline functionality for Android and iOS.",
    longDescription:
      "SAVIOUR Mobile is the essential mobile companion to the SAVIOUR disaster management platform, specifically designed to provide critical emergency response capabilities on mobile devices. Built with Flutter for seamless cross-platform compatibility, the app ensures users can access emergency services even in challenging network conditions through robust offline functionality. The application features advanced GPS integration for precise location tracking, push notification systems for immediate alerts, and offline data synchronization capabilities. It includes emergency contact management, disaster preparedness guides, and seamless integration with the web platform for comprehensive emergency response coverage.",
    technologies: [
      "Flutter",
      "Firebase",
      "Push Notifications",
      "Offline Storage",
      "GPS Integration",
      "Material UI",
      "SQLite",
      "REST APIs",
    ],
    features: [
      "Cross-platform compatibility (Android & iOS)",
      "Robust offline emergency functionality and data sync",
      "Real-time location sharing and tracking with GPS",
      "Advanced push notification system for critical alerts",
      "Comprehensive emergency contact management",
      "Offline disaster preparedness guides and resources",
      "Seamless integration with web platform",
      "User-friendly Material Design interface",
      "Emergency SOS features with one-touch activation",
      "Battery optimization for extended emergency use",
    ],
    image: "/saviour-mobile.jpg",
    github: "https://github.com/Ravikumar-2016/Saviour-App",
    featured: false,
  },
  {
    title: "Soil Sense",
    slug: "soil-sense",
    category: "AgriTech Solution",
    description:
      "An intelligent crop and fertilizer recommendation system that analyzes soil parameters and environmental conditions to suggest optimal crops and fertilizers using machine learning.",
    longDescription:
      "Soil Sense is an advanced agricultural recommendation system that leverages data science and machine learning to provide farmers with scientifically-backed crop and fertilizer recommendations. The system analyzes multiple environmental and soil parameters to optimize farming decisions, helping farmers increase yield while maintaining soil health. Built with modern web technologies and integrated with agricultural databases, Soil Sense provides personalized recommendations based on local conditions, soil composition, and climate patterns. The platform includes features for soil health monitoring, crop rotation planning, and sustainable farming practices, making it an essential tool for modern agriculture.",
    technologies: [
      "React",
      "TypeScript",
      "Node.js",
      "Express",
      "Tailwind CSS",
      "Machine Learning",
      "Chart.js",
      "MongoDB",
    ],
    features: [
      "Environmental parameter analysis (Temperature, Humidity, Rainfall)",
      "Soil condition assessment (pH Level, Carbon Content, Soil Type)",
      "Nutrient analysis (Nitrogen, Phosphorous, Potassium levels)",
      "AI-powered intelligent crop recommendation engine",
      "Scientific fertilizer type and quantity suggestions",
      "User-friendly input interface with real-time validation",
      "Responsive design optimized for all devices",
      "Data-driven recommendations with research backing",
    ],
    image: "/soilsense.jpg",
    github: "https://github.com/Ravikumar-2016/SoilSense",
    liveUrl: "https://soil-sense-phi.vercel.app",
    featured: false,
  },
  {
    title: "SkyNow",
    slug: "skynow",
    category: "Weather Application",
    description:
      "A minimalist weather web application providing real-time weather data using OpenWeatherMap API with location-based forecasting and clean UI.",
    longDescription:
      "SkyNow is a clean and minimalist weather application that delivers comprehensive weather information based on geographical coordinates. Built with vanilla JavaScript and modern web technologies, SkyNow offers real-time weather updates, detailed atmospheric conditions, and astronomical information. The application features a responsive design that works seamlessly across all devices and includes weather metrics essential for outdoor activities and daily planning.",
    technologies: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "OpenWeatherMap API",
      "Responsive Design",
      "Geolocation API",
    ],
    features: [
      "Weather search by Latitude & Longitude coordinates",
      "Real-time temperature and weather conditions",
      "Humidity levels and atmospheric pressure readings",
      "Wind speed and direction display",
      "UV Index and visibility information",
      "Sunrise and sunset timings",
      "Responsive and lightweight interface",
      "Geolocation integration",
    ],
    image: "/skynow.jpg",
    github: "https://github.com/Ravikumar-2016/SkyNow",
    liveUrl: "https://sky-now-three.vercel.app/",
    featured: false,
  },
  {
    title: "Driver Drowsiness Detection",
    slug: "driver-drowsiness-detection",
    category: "Computer Vision / ML",
    description:
      "A traditional computer vision system for detecting driver drowsiness using facial landmark detection and eye aspect ratio analysis to prevent accidents.",
    longDescription:
      "This Driver Drowsiness Detection System uses traditional computer vision techniques to monitor driver alertness and prevent accidents caused by fatigue. The system analyzes facial landmarks, particularly focusing on eye aspect ratios, to detect signs of drowsiness. When drowsiness is detected, the system triggers alerts to wake the driver. Built with Python and OpenCV, this project demonstrates practical applications of computer vision in road safety.",
    technologies: [
      "Python",
      "OpenCV",
      "dlib",
      "NumPy",
      "Facial Landmark Detection",
      "Eye Aspect Ratio Algorithm",
    ],
    features: [
      "Real-time facial landmark detection",
      "Eye aspect ratio (EAR) calculation",
      "Drowsiness level monitoring",
      "Audio alert system for drowsy drivers",
      "Configurable sensitivity thresholds",
      "Low latency real-time processing",
    ],
    image: "/drowsiness.jpg",
    github: "https://github.com/Ravikumar-2016/Traditional-Driver-Drowsiness-Detection-System",
    featured: false,
  },
  {
    title: "DDD System (ML Model)",
    slug: "ddd-system-ml",
    category: "Machine Learning",
    description:
      "A trained machine learning model for driver drowsiness detection using deep learning techniques for improved accuracy over traditional methods.",
    longDescription:
      "This is an advanced Driver Drowsiness Detection system that leverages trained machine learning models for improved accuracy and reliability. Unlike traditional computer vision approaches, this system uses deep learning to analyze driver behavior and detect fatigue patterns. The trained model provides better generalization across different lighting conditions and facial features, making it more robust for real-world deployment.",
    technologies: [
      "Python",
      "TensorFlow/Keras",
      "Deep Learning",
      "CNN",
      "Image Classification",
      "NumPy",
    ],
    features: [
      "Deep learning-based detection",
      "Trained CNN model for classification",
      "High accuracy drowsiness detection",
      "Robust to lighting variations",
      "Model inference optimization",
      "Dataset preprocessing pipeline",
    ],
    image: "/ddd-ml.jpg",
    github: "https://github.com/Ravikumar-2016/Trained-Model-DDD-System",
    featured: false,
  },
  {
    title: "FieldGrower",
    slug: "fieldgrower",
    category: "PHP Web Application",
    description:
      "A web-based agricultural management system built with PHP for managing farm operations, crop tracking, and agricultural data management.",
    longDescription:
      "FieldGrower is a comprehensive web-based agricultural management system built with PHP. The platform helps farmers and agricultural managers track crop cycles, manage farm operations, and maintain agricultural records. With a focus on usability and practical farm management needs, FieldGrower provides essential tools for modern farming operations.",
    technologies: [
      "PHP",
      "MySQL",
      "HTML5",
      "CSS3",
      "JavaScript",
      "Bootstrap",
    ],
    features: [
      "Crop cycle management and tracking",
      "Farm operations logging",
      "Agricultural data management",
      "User authentication system",
      "Database-driven records",
      "Responsive web interface",
    ],
    image: "/fieldgrower.jpg",
    github: "https://github.com/Ravikumar-2016/FieldGrower",
    featured: false,
  },
  {
    title: "Portfolio 2.0",
    slug: "portfolio-2-0",
    category: "Personal Website",
    description:
      "A modern, responsive portfolio website built with Next.js and TypeScript showcasing projects, skills, and professional experience with dark mode support.",
    longDescription:
      "Portfolio 2.0 is a modern, professionally designed personal portfolio website built with Next.js 15 and TypeScript. The website features a clean, responsive design with dark mode support, smooth animations using Framer Motion, and optimized performance. It showcases projects, technical skills, education, and provides easy ways to get in touch. The site demonstrates modern web development practices and UI/UX design principles.",
    technologies: [
      "Next.js 15",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "Radix UI",
      "Vercel",
    ],
    features: [
      "Modern responsive design",
      "Dark/Light mode toggle",
      "Smooth page animations",
      "Project showcase with details",
      "Skills and education sections",
      "Contact information integration",
      "SEO optimized",
      "Fast page loads with Next.js",
    ],
    image: "/portfolio.jpg",
    github: "https://github.com/Ravikumar-2016/Portfolio2.O",
    liveUrl: "https://portfolio-sigma-mu-70.vercel.app/",
    featured: false,
  },
]
